[versions]
accompanist-swiperefresh = "0.24.13-rc"
agp = "8.2.2"
kotlin = "1.9.10"
compose = "1.5.1"
compose-coil = "2.5.0"
compose-compiler = "1.5.3"
compose-material3 = "1.1.2"
compose-navigation = "2.7.5"
androidx-activity-compose = "1.7.2"
androidx-lifecycle-viewmodel = "2.6.2"
koin = "3.4.3"
kotlinx-coroutines-core = "1.7.3"
kotlinx-datetime = "0.4.1"
ktor-client = "2.3.5"
sql-delight = "2.0.0"

[libraries]
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist-swiperefresh" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name="lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose",version.ref = "compose-navigation" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor-client" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref="ktor-client"}
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref="ktor-client"}
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref="ktor-client"}
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref="ktor-client"}
sql-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sql-delight" }
sql-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sql-delight" }
sql-native-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sql-delight" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sql-delight" }
